# Travis configuration file
---
dist: xenial

language: bash

addons:
    apt_packages:
        - autoconf
        - autoconf-archive
        - automake
        - autotools-dev
        - build-essential
        - cmake
        - curl
        - git
        - libarmadillo-dev
        - libatlas-cpp-0.6-dev
        - libboost-all-dev
        - liblapack-dev
        - libnlopt0
        - libnlopt-dev
        - libopenmpi-dev
        - libopenblas-dev
        - libtool
        - openmpi-bin
        - tzdata
        - wget
        - xvfb

cache:
    timeout: 1000
    directories:
        - "$HOME/miniconda3_$TRAVIS_OS_NAME"
        - "$TRAVIS_BUILD_DIR/.snakemake/conda"  # snakemake envs

before_install: |
    bash .travis/before_install.sh

install: |
    bash .travis/install.sh

script: |
    bash .travis/script.sh

before_cache: |
    bash .travis/before_cache.sh

# after_failure:
    # bash .travis/after_failure.sh
