# Travis configuration file
---
dist: trusty

language: bash

addons:
    apt_packages:
        - build-essential
        - git
        - curl

cache:
    timeout: 1000
    directories:
        - "$HOME/miniconda3_$TRAVIS_OS_NAME"
        - "$TRAVIS_BUILD_DIR/.snakemake/conda"  # Conda cache!

before_install:
    - bash .travis/travis_before_install.sh

install:
    - bash .travis/travis_install.sh

script:
    - echo $PATH
    - python --version
    - export PATH="$HOME"/miniconda3_"$TRAVIS_OS_NAME"/bin:"$PATH"
    - CONDA_PATH="$HOME"/miniconda3_"$TRAVIS_OS_NAME"
    - snakemake --use-conda --jobs 2
    - snakemake --cleanup-conda

before_cache:
    - CONDA_PATH="$HOME"/miniconda3_"$TRAVIS_OS_NAME"
    - conda clean --all --yes
    - rm -rf "$CONDA_PATH"/{locks,pkgs,var,conda-meta/history}

after_failure:
    cat data/downloads/uniprot_sprot.log
