# Travis configuration file
---
dist: xenial

language: bash

addons:
    apt_packages:
        - build-essential
        - git
        - curl
        - autotools-dev
        - autoconf
        - autoconf-archive
        - automake
        - cmake
        - libtool
        - liblapack-dev
        - libatlas-cpp-0.6-dev
        - libnlopt-dev
        - libnlopt0
        - libarmadillo-dev
        - libopenmpi-dev
        - openmpi-bin
        - wget
        - xvfb

 cache:
     timeout: 1000
     directories:
         - "$HOME/miniconda3_$TRAVIS_OS_NAME"
         - "$TRAVIS_BUILD_DIR/.snakemake/conda"  # snakemake envs

before_install: |
    url="https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh"
    if [[ -d "$HOME"/miniconda3_"$TRAVIS_OS_NAME"/bin ]]; then
        echo "miniconda already installed."
    else
        echo "Installing miniconda."
        mkdir -p "$HOME"/download
        wget \
            --continue \
            --output-document "$HOME"/download/miniconda_"$TRAVIS_OS_NAME".sh \
            $url
        chmod +x "$HOME"/download/miniconda_"$TRAVIS_OS_NAME".sh
        "$HOME"/download/miniconda_"$TRAVIS_OS_NAME".sh \
            -u \
            -b \
            -p "$HOME"/miniconda3_"$TRAVIS_OS_NAME"
        "$HOME"/miniconda3_"$TRAVIS_OS_NAME"/bin/conda clean --all --yes
        echo "local_repodata_ttl: 1800" >> ~/.condarc
    fi

install: |
    export PATH="$HOME"/miniconda3_"$TRAVIS_OS_NAME"/bin:"$PATH"
    echo "$PATH"
    conda config --add channels defaults
    conda config --add channels conda-forge
    conda config --add channels bioconda
    conda install --quiet --yes --channel bioconda snakemake=5.12.3
    snakemake --use-conda --create-envs-only
    conda clean --all --yes
    mkdir -p bin/
    pushd src/phyx-1.01/src
    ./configure
    make
    cp px* ../../../bin/
    popd
    pushd src/guidance.v2.02/programs
    make -j 2
    popd

script: |
    echo $PATH
    python --version
    export PATH="$HOME"/miniconda3_"$TRAVIS_OS_NAME"/bin:"$PATH"
    snakemake --use-conda --jobs 2 --show-failed-logs

before_cache: |
    snakemake --cleanup-conda
    conda clean --all --yes
    rm -rf results/
    rm -rf "$CONDA_PATH"/{locks,pkgs,var,conda-meta/history}

after_failure:
