# Snakemake parameter configuration file
---
max_threads: 24

cd-hit:
    threshold: 0.995  # Identity threshold to merge proteins

orthofinder:
    blastp_evalue: 0.001
    mcl_inflation: 1.5
    msa_program: mafft
    tree_program: fasttree

homologs:
    pxclsq:
        min_occupancy: 0.1
    trim_tips:
        relative_cutoff: 10
        absolute_cutoff: 2
    mask_tips:
        mask_paraphyletic: "y"
    cut_internal_long_branches:
        internal_branch_cutoff: 0.5
        minimum_taxa: 3
    root_to_tip:
        minimum_ingroup_taxa: 3

tree:
    min_occupation: 0.5
    raxml:
        bootstrap_replicates: 1000

fastcodeml:
    maximizer: 22
