# Snakemake parameter configuration file
---
transdecoder:
    chunks: 1  # Same for blastx and hmmscan
    blastp:
        database: swissprot  # or uniref90
        evalue: 1e-5
        max_target_seqs: 1
    hmmscan:
    predict:

cd-hit:
    threshold: 0.995  # Identity threshold to merge proteins


orthofinder:
    blastp_evalue: 0.001
    number_of_chunks: 1
    mcl_inflation: 1.5
    msa_program: mafft
    tree_program: fasttree

homologs:
    trim_tips:
        relative_cutoff: 0.2
        absolute_cutoff: 0.4
    mask_tips:
        mask_paraphyletic: "y"
    cut_internal_long_branches:
        internal_branch_cutoff: 0.5
        minimum_taxa: 3

fastcodeml:
    maximizer: 22
