# Snakemake parameter configuration file
---
max_threads: 24

cd-hit:
    threshold: 0.995  # Identity threshold to merge proteins

orthofinder:
    blastp_evalue: 0.001
    mcl_inflation: 1.5
    msa_program: mafft
    tree_program: fasttree

homologs:
    pxclsq:
        min_occupancy: 0.1
    trim_tips:
        relative_cutoff: 10
        absolute_cutoff: 2
    mask_tips:
        mask_paraphyletic: "y"
    cut_internal_long_branches:
        internal_branch_cutoff: 0.5
        minimum_taxa: 3
    root_to_tip:
        minimum_ingroup_taxa: 3

tree:
    supermatrix:
        min_taxa: 4  # Raxml requires at least 4
        min_length: 0  # 0 if 4d sites, 300 for codons, 100 for aa
    min_occupation: 0.5
    raxml:
        threads: 1
        bootstrap_replicates: 1000
    executables:
        exabayes: "./bin/exabayes"  # "./bin/yggdrasil"
        sdsf: "./bin/sdsf"
        postprocparam: "./bin/postProcParam"
        tracer: "tracer"
        consense: "./bin/consense"
    exabayes:
        mcmc_runs: 4
        coupled_chains: 3
        generations: 1000  # 1e6
        sampling_frequency: 500  # 1000 by default
        threads: 1
    outgroup: spil

selection:
    foreground_branches:
       clupeinae:
            species: "char,cpal"
            models: "bsA bsA1"

    ete3:
        min_foreground: 2  # Number of species needed for the foreground branch
        min_background: 2  # Number of species needed for the background branch
        omega_zeros: "0.5,1.0,1.5"  # Starting values for ML optimization
        evalue: 0.05  # e-value to say that a test is significant
        binary: "bin/codeml"
    guidance:
        msa_program: "PRANK"
        program: "GUIDANCE2"
        bootstraps: 5
        genetic_code: 1
        sequence_cutoff: 0.6
        column_cutoff: 0.93
        sequence_type: codon
    fastcodeml:
        min_foreground: 2  # Number of species needed for the foreground branch
        min_background: 2  # Number of species needed for the background branch
        omega_zeros: "0.5,1.0,1.5"  # Starting values for ML optimization
        evalue: 0.05  # e-value to say that a test is significant
        binary: "./bin/fast"

fastcodeml:
    maximizer: 22
